### ISSUE TITLE
Download software not showing up

### ISSUE THREAD

**Issue by jeroentjesgit** [kubesail/pibox-os#1]
Hi when I go to the page to download the latest release it isn't there does that mean that the software not available is to the public to download or do I do have something wrong?

**Comment by erulabs** [comment]
Hey @Pimaster3 - We're getting ready to ship the first pre-built images soon - they'll show up here in the "releases" tab. For now, you can use this repo to build your own image, but we should have the close-to-final image uploaded in the next few days!

Thank you for your interest :D ❤️

**Comment by jeroentjesgit** [comment]
@erulabs thanks I'm looking forward to it!

**Comment by pastudan** [comment]
hey @Pimaster3 we released this a few days ago at https://github.com/kubesail/pibox-os/releases/tag/untagged-d7743546ef7be69e059f. Thanks!
